version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
   configuration: docs/conf.py


python:
   install:
   - method: pip
     path: .
   - requirements: docs_requirements.txt
