name: Test
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.rst'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.rst'
jobs:
  test:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: .github/workflows/test.yml
      - run: |
          python -m pip install -U pip
          pip install -U wheel setuptools
      - run: pip install tox==3.27.1 tox-gh-actions
      - run: tox
